# Leaf1 configuration without Predictive Cache (for comparison)

[server]
listen = "[::]:4444"
tls.generate = ["localhost"]

[web.http]
listen = "[::]:4444"

[cluster]
root = "localhost:4443"
token = "dev/root.jwt"
node = "localhost:4444"

# Predictive cache disabled
[cluster.predictive_cache]
enabled = false

[client.tls]
disable_verify = true

[auth]
key = "dev/root.jwk"
public = "anon"
