[log]
level = "debug"

[server]
listen = "[::]:4445"
tls.generate = ["localhost", "100.81.137.8"]

[web.https]
listen = "[::]:4445"
cert = "dev/certs/cert.pem"
key = "dev/certs/key.pem"

[cluster]
connect = "localhost:4443"
token = "dev/root.jwt"
node = "localhost:4445"

[client.tls]
disable_verify = true

[auth]
key = "dev/root.jwk"
public = "anon"
